#VARIANTS="CLANG13,OPENMP-OFF CLANG17,OPENMP-OFF CLANG16,OPENMP-OFF CLANG12,OPENMP-OFF CLANG11,OPENMP-OFF CLANG10,OPENMP-OFF CLANG9,OPENMP-OFF CLANG15,OPENMP-OFF CLANG14,OPENMP-OFF GCC11,OPENMP-OFF GCC10,OPENMP-OFF GCC9,OPENMP-OFF"
VARIANTS="CLANG13,OPENMP-OFF CLANG13,OPENMP-OFF,HEXL-OFF"
