# LONG LIST
#VARIANTS="GCC9 GCC10 GCC11 CLANG10 CLANG11 CLANG12 GCC9,HEXL-ON,NATIVEOPT-ON GCC10,HEXL-ON,NATIVEOPT-ON GCC10,HEXL-ON,NATIVEOPT-ON CLANG10,HEXL-ON,NATIVEOPT-ON CLANG11,HEXL-ON-NATIVEOPT-ON CLANG11,HEXL-ON-NATIVEOPT-ON"

# NOT-AS-LONG LIST
#VARIANTS="GCC9 GCC9,HEXL-ON,NATIVEOPT-ON GCC10,HEXL-ON,NATIVEOPT-ON GCC11,HEXL-ON,NATIVEOPT-ON CLANG10,HEXL-ON,NATIVEOPT-ON CLANG11,HEXL-ON,NATIVEOPT-ON CLANG12,HEXL-ON,NATIVEOPT-ON"

# FOR PROFILING WORK
VARIANTS="GCC9 CLANG11,NATIVEOPT-ON CLANG11,NATIVEOPT-ON,HEXL-ON CLANG11,NATIVEOPT-ON,HEXL-ON,OMP-OFF"
